### ISSUE TITLE
Safari reports invalid date in Time Till Goal Reached

### ISSUE THREAD

**Issue by dantheother** [nathakits/covid-thai-website#59]
![image](https://user-images.githubusercontent.com/4437255/128456071-715e9364-1b42-41dd-a1f5-effd460e1aa6.png)

I think it's to do with the way dates are parsed - safari cannot parse strings like `2022-5-26`

https://github.com/nathakits/covid-thai-website/blob/main/components/VaccineTarget.vue#L144

Code like

```
const day = date.getDate()
const month = date.getMonth() + 1
const year = date.getFullYear()
const goalDate = `${year}-${month}-${day}`
const formatGoalDate = new Date(goalDate).toLocaleDateString("en-us", {
  day: "numeric",
  month: "short",
  year: "numeric",
})
```

Should probably be simplified to
```
const formatGoalDate = new Date(date.getDate(), date.getMonth(), date.getFullYear()).toLocaleDateString("en-us", {
  day: "numeric",
  month: "short",
  year: "numeric",
})
```

Or, if the intermediate variables are important, pad the month to 2 digits

```
const goalDate = `${year}-${month < 10 : "0" + month : month}-${day}`
```

**Comment by nathakits** [comment]
Hi. Thanks for the bug report. I will check it this weekend.

**Comment by nathakits** [comment]
Looks good! Merged.
